
package ro.ucv.inf.soa.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://service.ws.soa.inf.ucv.ro/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://service.ws.soa.inf.ucv.ro/", className = "ro.ucv.inf.soa.ws.service.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://service.ws.soa.inf.ucv.ro/", className = "ro.ucv.inf.soa.ws.service.SumResponse")
    @Action(input = "http://service.ws.soa.inf.ucv.ro/CalculatorService/sumRequest", output = "http://service.ws.soa.inf.ucv.ro/CalculatorService/sumResponse")
    public int sum(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "diference", targetNamespace = "http://service.ws.soa.inf.ucv.ro/", className = "ro.ucv.inf.soa.ws.service.Diference")
    @ResponseWrapper(localName = "diferenceResponse", targetNamespace = "http://service.ws.soa.inf.ucv.ro/", className = "ro.ucv.inf.soa.ws.service.DiferenceResponse")
    @Action(input = "http://service.ws.soa.inf.ucv.ro/CalculatorService/diferenceRequest", output = "http://service.ws.soa.inf.ucv.ro/CalculatorService/diferenceResponse")
    public int diference(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
