
package ro.ucv.inf.soa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://ws.soa.inf.ucv.ro/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {


    /**
     * 
     * @param guestname
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.soa.inf.ucv.ro/HelloWorld/sayHelloRequest", output = "http://ws.soa.inf.ucv.ro/HelloWorld/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "guestname", partName = "guestname")
        String guestname);

}
